<?php

namespace ContainerGbZM1o1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M4DR7F4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m4DR7F4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m4DR7F4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'recettesRepository' => ['privates', 'App\\Repository\\RecettesRepository', 'getRecettesRepositoryService', true],
        ], [
            'doctrine' => '?',
            'recettesRepository' => 'App\\Repository\\RecettesRepository',
        ]);
    }
}
