<?php

namespace ContainerGbZM1o1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FD2fcmzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FD2fcmz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FD2fcmz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\RequestController::editRecipe' => ['privates', '.service_locator.m4DR7F4', 'get_ServiceLocator_M4DR7F4Service', true],
            'App\\Controller\\RequestController::getRecipes' => ['privates', '.service_locator.Mg770zM', 'get_ServiceLocator_Mg770zMService', true],
            'App\\Controller\\RequestController::modifyRecipe' => ['privates', '.service_locator.Mg770zM', 'get_ServiceLocator_Mg770zMService', true],
            'App\\Controller\\RequestController::postRecipes' => ['privates', '.service_locator.m4DR7F4', 'get_ServiceLocator_M4DR7F4Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\RequestController:editRecipe' => ['privates', '.service_locator.m4DR7F4', 'get_ServiceLocator_M4DR7F4Service', true],
            'App\\Controller\\RequestController:getRecipes' => ['privates', '.service_locator.Mg770zM', 'get_ServiceLocator_Mg770zMService', true],
            'App\\Controller\\RequestController:modifyRecipe' => ['privates', '.service_locator.Mg770zM', 'get_ServiceLocator_Mg770zMService', true],
            'App\\Controller\\RequestController:postRecipes' => ['privates', '.service_locator.m4DR7F4', 'get_ServiceLocator_M4DR7F4Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\RequestController::editRecipe' => '?',
            'App\\Controller\\RequestController::getRecipes' => '?',
            'App\\Controller\\RequestController::modifyRecipe' => '?',
            'App\\Controller\\RequestController::postRecipes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\RequestController:editRecipe' => '?',
            'App\\Controller\\RequestController:getRecipes' => '?',
            'App\\Controller\\RequestController:modifyRecipe' => '?',
            'App\\Controller\\RequestController:postRecipes' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
