<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGbZM1o1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGbZM1o1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGbZM1o1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGbZM1o1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGbZM1o1\App_KernelDevDebugContainer([
    'container.build_hash' => 'GbZM1o1',
    'container.build_id' => '2f677da0',
    'container.build_time' => 1654343213,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGbZM1o1');
